# Generated by Django 5.2.8 on 2025-12-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products_inventory',
        ),
    ]
