# Generated by Django 5.2.8 on 2025-12-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products_product',
        ),
    ]
