# Generated by Django 5.2.8 on 2025-12-22 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ramo',
        ),
    ]
