# Generated by Django 5.2.8 on 2025-12-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='teste_deploy',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
