# Generated by Django 5.2.8 on 2025-12-23 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sector',
        ),
        migrations.AddField(
            model_name='client',
            name='business_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.businesssector'),
        ),
        migrations.AlterModelTable(
            name='client',
            table='customers_client',
        ),
    ]
