# Generated by Django 5.2.8 on 2025-12-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_client_teste_deploy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='teste_deploy',
        ),
    ]
