# Generated by Django 5.2.8 on 2025-12-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_client_teste_deploy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='sector',
            new_name='business_sector',
        ),
        migrations.AlterModelTable(
            name='client',
            table='customers_client',
        ),
    ]
